services:
  smartwchr:
    image: makaspacex/smartwchr:dev
    container_name: smartwchr
    network_mode: host
    privileged: true
    working_dir: /ros2_ws
    volumes:
      - ./:/ros2_ws
      - /dev/imu_usb:/dev/imu_usb
      - /dev/oradar:/dev/oradar
      - /dev/driver:/dev/driver
      - /dev/encoder_left:/dev/encoder_left
      - /dev/encoder_right:/dev/encoder_right
    environment:
      - TZ=Asia/Shanghai
    command: "/bin/zsh -c 'source ~/.zshrc && make launch wcmain sensor_pub.py'"
