services:
  smartwchr:
    image: makaspacex/smartwchr:dev
    container_name: smartwchr
    network_mode: host
    privileged: true
    working_dir: /ros2_ws
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/oradar:/dev/oradar
      - /dev/rplidar:/dev/rplidar
      - /dev/driver:/dev/driver
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    environment:
      - TZ=Asia/Shanghai
    command: "/bin/zsh -c 'source ~/.zshrc && make launch swc_nav_bringup bringup_sensor.launch.py'"
