services:
  Sensors:
    image: makaspacex/smartwchr:dev
    container_name: smartwchr
    network_mode: host
    privileged: true
    working_dir: /ros2_ws
    volumes:
      - ./src:/ros2_ws/src
      - ./makefile:/ros2_ws/makefile
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB1:/dev/imu_usb
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB2:/dev/oradar
    environment:
      - TZ=Asia/Shanghai
      - CUID=0
    command: "/bin/zsh -c 'source ~/.zshrc && make build wc && source ~/.zshrc && make launch wcmain sensor_pub.py'"
