ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    # map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint # the frame id used by the turtlebot's diff drive plugin
    world_frame: odom
    odom0: /Odometry
    odom0_config: [true,  true,  false,        # 位置
                    false, false, true,         # 角度
                    false, false, false,        # 速度
                    false, false, false,        # 角速度
                    false, false, false]        # 加速度
    odom0_queue_size: 10
