FROM makaspacex/smartwchr:base

ARG USERNAME=rosdev
ARG UID=1000
ARG GID=$UID

USER root
RUN apt update -q && apt install -y --no-install-recommends \
    ros-$ROS_DISTRO-pcl-ros ros-$ROS_DISTRO-pluginlib  ros-$ROS_DISTRO-pcl-conversions \
    libpcap-dev libboost1.74-dev

USER $USERNAME
# Create workspace so that user own this directory
RUN sudo mkdir -p /home/$USERNAME/ros2_ws && sudo chown ${USERNAME}:${USERNAME} /home/$USERNAME/ros2_ws
WORKDIR /home/$USERNAME/ros2_ws

# Copy configuration files
COPY ./ros2init.sh /tmp
RUN cat /tmp/ros2init.sh >> ~/.zshrc && sudo rm -f /tmp/ros2init.sh

CMD ["zsh"]
