FROM makaspacex/smartwchr:base

ENV ROS_DISTRO=humble

# slam and wheel describesion
RUN apt update &&  \
    apt install -y --no-install-recommends \
    ros-$ROS_DISTRO-robot-state-publisher \
    ros-$ROS_DISTRO-joint-state-publisher-gui \
    ros-$ROS_DISTRO-cartographer ros-$ROS_DISTRO-cartographer-ros \
    python3-argcomplete ros-$ROS_DISTRO-tf-transformations ros-$ROS_DISTRO-robot-localization && \
    apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# imu
RUN pip3 config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple \
    && pip3 install pyserial numpy rich

RUN apt update &&  \
    apt install -y --no-install-recommends \
    ros-$ROS_DISTRO-desktop-full && \
    apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# update 
COPY ./ros_shell.sh ~/
RUN echo '[[ -f ~/.ros_shell.sh ]] && source ~/.ros_shell.sh' > ~/.zshrc

# Create workspace so that user own this directory
WORKDIR /ros2_ws

# set entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["zsh"]
