
services:
  smartwchr:
    image: makaspacex/smartwchr:dev
    container_name: smartwchr
    network_mode: host
    privileged: true
    volumes:
      - ../src:/ros2_ws/src
      - ../makefile:/ros2_ws/makefile
    environment:
      - TZ=Asia/Shanghai
    command: "/bin/zsh"
